### ISSUE TITLE
Android + Fabric : ANR on TextInput

### ISSUE THREAD

**Issue by mlecoq** [kirillzyusko/react-native-keyboard-controller#687]
**Describe the bug**
Since my app is on fabric, I have many ANR on text input

here is one of the stack traces 

```
io.sentry.android.core.ApplicationNotResponding: ANR
    atsyscall
    at__futex_wait_ex
    atNonPI::MutexLockWithTimeout
    atoffset 4a8000) (std::__ndk1::mutex::lock
    atoffset 12b8000) (facebook::react::Binding::schedulerDidFinishTransaction
    atoffset 12b8000) (facebook::react::Scheduler::uiManagerDidFinishTransaction
    atoffset 12b8000) (facebook::react::UIManager::shadowTreeDidFinishTransaction const
    atoffset 12b8000) (facebook::react::ShadowTree::mount const
    atoffset 12b8000) (facebook::react::ShadowTree::tryCommit const
    atoffset 12b8000) (facebook::react::ShadowTree::commit const
    at
    atoffset 12b8000) (facebook::react::ShadowTreeRegistry::visit const
    atoffset 1900000) (reanimated::NativeReanimatedModule::performOperations
    atoffset 1900000) (facebook::jni::detail::MethodWrapper<void , &reanimated::NativeProxy::performOperations, reanimated::NativeProxy, void>::dispatch
    atoffset 1900000) (facebook::jni::detail::FunctionWrapper<void , facebook::jni::detail::JTypeFor<facebook::jni::HybridClass<reanimated::NativeProxy, facebook::jni::detail::BaseHybridClass>::JavaPart, facebook::jni::JObject, void>::_javaobject*, void>::call
    at com.swmansion.reanimated.NativeProxy.performOperations
    at com.swmansion.reanimated.NodesManager.performOperations(NodesManager.java:225)
    at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:337)
    at com.facebook.react.uimanager.events.FabricEventDispatcher.dispatchEvent(FabricEventDispatcher.java:71)
    at com.reactnativekeyboardcontroller.extensions.ThemedReactContextKt.dispatchEvent(ThemedReactContext.kt:23)
    at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver.dispatchEventToJS(FocusedInputObserver.kt:163)
    at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver.syncUpLayout(FocusedInputObserver.kt:153)
    at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver.layoutListener$lambda$0(FocusedInputObserver.kt:57)
    at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver.$r8$lambda$l4n8HFqvwhvLaxfgqXOCa3idsFI(unavailable:0)
    at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver$$ExternalSyntheticLambda0.onLayoutChange(D8$$SyntheticClass:0)
    at android.view.View.layout(View.java:25180)
    at com.facebook.react.fabric.mounting.SurfaceMountingManager.updateLayout(SurfaceMountingManager.java:849)
    at com.facebook.react.fabric.mounting.mountitems.IntBufferBatchMountItem.execute(IntBufferBatchMountItem.java:140)
    at com.facebook.react.fabric.mounting.MountItemDispatcher.executeOrEnqueue(MountItemDispatcher.java:387)
    at com.facebook.react.fabric.mounting.MountItemDispatcher.dispatchMountItems(MountItemDispatcher.java:293)
    at com.facebook.react.fabric.mounting.MountItemDispatcher.tryDispatchMountItems(MountItemDispatcher.java:126)
    at com.facebook.react.fabric.FabricUIManager$3.runGuarded(FabricUIManager.java:831)
    at com.facebook.react.bridge.GuardedRunnable.run(GuardedRunnable.java:29)
    at com.facebook.react.fabric.FabricUIManager.scheduleMountItem(FabricUIManager.java:835)
    at com.facebook.react.fabric.BindingImpl.reportMount
    at com.facebook.react.fabric.FabricUIManager$MountItemDispatchListener$1.run(FabricUIManager.java:1276)
    at android.os.Handler.handleCallback(Handler.java:959)
    at android.os.Handler.dispatchMessage(Handler.java:100)
```

it always deal with

```
   at com.facebook.react.uimanager.events.FabricEventDispatcher.dispatchEvent(FabricEventDispatcher.java:71)
   at com.reactnativekeyboardcontroller.extensions.ThemedReactContextKt.dispatchEvent(ThemedReactContext.kt:23)
   at com.reactnativekeyboardcontroller.listeners.FocusedInputObserver.dispatchEventToJS(FocusedInputObserver.kt:163)
```

and the issue is not systematic (first try sometimes works fine)

**Code snippet**
I don't use directly the api on concerned screen, I just have `KeyboardProvider` in my `App.tsx` file

**Repo for reproducing**
I will try to make one soon

**To Reproduce**

1. Go to screen with input text
2. Tap on it (to get focus)
3. The app is frozen

**Smartphone (please complete the following information):**

- Desktop OS: macOs 14.6.1
- Device: reproduced on several devices: Samsung (phones and tabs), Redmi ...
- OS: Android 14
- RN version: 0.76.1
- RN architecture: new 
- JS engine: Hermes
- Library version: 1.14.4

**Comment by kirillzyusko** [comment]
@mlecoq which reanimated version do you use?

`keyboard-controller` intercepts `TextInput` events, so when you focus input or blur it then `keyboard-controller` will intercept these events and will dispatch them to JS as well... But I'm really curious how it can produce race conditions 🤔

**Comment by mlecoq** [comment]
seems to be related to https://github.com/kirillzyusko/react-native-keyboard-controller/issues/683 - when I remove animated components on the screen, the crash does not occur

**Comment by mlecoq** [comment]
> @mlecoq which reanimated version do you use?
> 
> `keyboard-controller` intercepts `TextInput` events, so when you focus input or blur it then `keyboard-controller` will intercept these events and will dispatch them to JS as well... But I'm really curious how it can produce race conditions 🤔

3.16.1

**Comment by kirillzyusko** [comment]
@mlecoq I spoke with @tomekzaw and he told me that the problem most likely is the same as https://github.com/software-mansion/react-native-reanimated/issues/6418#issuecomment-2296107100

Can you try to build RN from source and enable `allowRecursiveCommitsWithSynchronousMountOnAndroid` flag? This flag should be enabled by default starting from RN 0.77, but in a meantime the only one solution is to patch it and build from source 😔

**Comment by mlecoq** [comment]
Ok I will try that, thanks @kirillzyusko

**Comment by kirillzyusko** [comment]
@mlecoq please, keep me updated how it goes 🙏

**Comment by mlecoq** [comment]
@kirillzyusko I confirm that the flag fixes this issue and #683

**Comment by kirillzyusko** [comment]
@mlecoq awesome! Did you built RN from source? Or found the other way to enable this flag?

**Comment by mlecoq** [comment]
I had to build rn from source

**Comment by dhruvbhatia** [comment]
Is there a way to build RN from source + enable the flag when within an Expo project?

**Comment by cjones26** [comment]
> Is there a way to build RN from source + enable the flag when within an Expo project?

I would also like to know this.

**Comment by kirillzyusko** [comment]
@dhruvbhatia @cjones26 I don't think it's possible, to be honest (but if you find a way - let me know).

One thing you can do is temporarily disable new arch (until new Expo SDK with RN 0.77+) and when new Expo SDK will be released you can enable newArch again 👀

**Comment by kirillzyusko** [comment]
@dhruvbhatia @cjones26 Okay, yesterday a new release of RN was published with a necessary cherry-pick, so I believe if you are using latest Expo SDK (52), then you can simply update `react-native` in your `package.json` and it should do the trick! Let me know if it works or not 👀

**Comment by cjones26** [comment]
@kirillzyusko nice, it does look like 0.76.6 has the fix:

https://github.com/facebook/react-native/releases/tag/v0.76.6

We'll give it a shot and look to see whether it fixes the issue.

Thanks!
