### ISSUE TITLE
Keyboard animation progress may be infinite and crash app

### ISSUE THREAD

**Issue by matthieuMay** [kirillzyusko/react-native-keyboard-controller#739]
**Describe the bug**
In production we randomly see a crash with the following stack trace
java.lang.RuntimeException: folly::toJson: JSON object value was an INF when serializing value at "progress"
    at com.facebook.react.bridge.NativeMap.toString(NativeMap.kt)
    at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java)
    at com.swmansion.reanimated.nativeProxy.EventHandler.receiveEvent(EventHandler.java:25)
    at com.facebook.react.uimanager.events.Event.dispatch(Event.java:173)
    at com.swmansion.reanimated.NodesManager.handleEvent(NodesManager.java:350)
    at com.swmansion.reanimated.NodesManager.onEventDispatch(NodesManager.java:336)
    at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent(EventDispatcherImpl.java:119)
    at com.reactnativekeyboardcontroller.extensions.ThemedReactContextKt.dispatchEvent(ThemedReactContext.kt:23)
    **at com.reactnativekeyboardcontroller.listeners.KeyboardAnimationCallback.onProgress(KeyboardAnimationCallback.kt:267)**
    at androidx.core.view.WindowInsetsAnimationCompat$Impl21.dispatchOnProgress(WindowInsetsAnimationCompat.java:922)
    at androidx.core.view.WindowInsetsAnimationCompat$Impl21$Impl21OnApplyWindowInsetsListener$1.onAnimationUpdate(WindowInsetsAnimationCompat.java:832)
    at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1558)
    at android.animation.ValueAnimator.animateBasedOnTime(ValueAnimator.java:1349)
    at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1481)
    at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
    at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
    at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1278)
    at android.view.Choreographer.doCallbacks(Choreographer.java:1019)
    at android.view.Choreographer.doFrame(Choreographer.java:907)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1248)
    at android.os.Handler.handleCallback(Handler.java:900)
    at android.os.Handler.dispatchMessage(Handler.java:103)
    at android.os.Looper.loop(Looper.java:219)

This error is rare (like 1 out of 10000 sessions) and we did not find a way to reproduce it. It is due to an incomplete numerical consistency check in KeyboardAnimationCallback.onProgress.

We made a patch package and release it to production. It fixes the issue.
I will submit a PR with the fin in a few minutes

**Comment by kirillzyusko** [comment]
@matthieuMay which version of the lib do you use?

**Comment by matthieuMay** [comment]
1.14.5
